import { Poppins } from "next/font/google";
import "./globals.css";



const poppins = Poppins({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`m-15 ${poppins.variable} antialiased`}>
        {/* Navigation Bar */}
        <nav className="navbar">
          <div className="nav-container">
            <h1 className="logo">Rachal's Place</h1>
            <ul className="nav-links">
              <li>Home</li>
              <li>About</li>
              <li>Contact</li>
            </ul>
          </div>
        </nav>
        
         {/* Main Content */}
        <div className="scroll-container content">
        {children}
      </div>
      
      </body>
    </html>
  );
}
